### ISSUE TITLE
StronglyTypedId Model Validation Problem

### ISSUE THREAD

**Issue by simonare** [andrewlock/StronglyTypedId#28] opened 2021-01-28 16:00 UTC
When I use OrderId in Controller/Action with wrong value (invalid guid), expected behavior is to fire a validation error. But the current behavior does not get into the validation and throws exception on 

```
public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
{
    var guid = serializer.Deserialize<System.Guid>(reader); <------ here
    return new ReferralId(guid);
}
```

sample code for demonstration

```
public IActionResult (MyModel model){
     if (!ModelState.IsValid)
           return BadRequest(ModelState)

    .....
}
```

This throws exception before entering Action

```
[17:57:09 ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at ReferralId.ReferralIdNewtonsoftJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\ASB\source\Workspaces\Workspace\Atlas\Atlas\Atlas.Module.HR\obj\Debug\net5.0\ReferralEntity.K3SYoa3Q.generated.cs:line 84
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Atlas.Infrastructure.Middleware.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in C:\ASB\source\Workspaces\Workspace\Atlas\Atlas\Atlas.Infrastructure\Middleware\ExceptionHandlingMiddleware.cs:line 24
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)

```

**Comment by andrewlock** [comment] 2021-01-31 23:22
Hi, I've just looked into this, and I'm not seeing the behaviour you describe. I get the following instead: `{"errors":{"Id":["The input was not valid."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-178ffe77da6fa2408972829c0b066e41-6f1bd7f9f052d84e-00"}`

**Comment by andrewlock** [comment] 2021-11-26 22:10
Closing this as I can't reproduce it - feel free to reopen if you have any more detatils

**Closed by andrewlock** 2021-11-26 22:10 UTC
